name: Release to Production Environment
on:
  push:
    branches:
      - main

jobs:
  job1:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@master # １
        with: # ２ アクションの入力パラメータを指定
          host: ${{ secrets.SSH_HOST2 }} # ホスト名
          username: ${{ secrets.SSH_USERNAME2 }} # SSH ユーザ名
          key: ${{ secrets.SSH_PRIVATE_KEY }} # 秘密鍵の内容
          port: ${{ secrets.SSH_PORT }} # ポート番号
          script: |
            cd /opt/bitnami/apache2/htdocs/music_vibe_app
            git switch main
            git pull origin main
            composer install
            php artisan migrate
